builds:
  - hooks:
      pre:
        - go get -u github.com/gobuffalo/packr/v2/packr2
        - make ui
        - packr2
        - sleep 5
brews:
  - name: "cosm"
    description: "CLI tool for developing Cosmos SDK apps."
    homepage: "https://github.com/allinbits/cosm"
    github:
      owner: "allinbits"
      name: "homebrew-tap"
    install: |
      bin.install "cosm"
