builds:
  - main: ./main.go
    hooks:
      pre:
        - cmd: make ui
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X "github.com/allinbits/cosm/runtime.Version={{.Tag}}"
    goos:
      - darwin
    goarch:
      - amd64
      - 386
archives:
  - replacements:
      "386": i386
      darwin: Darwin
      amd64: x86_64
checksum:
  name_template: checksums.txt
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
brews:
  - name: "cosm"
    description: "CLI tool for developing Cosmos SDK apps."
    homepage: "https://github.com/allinbits/cosm"
    github:
      owner: "allinbits"
      name: "homebrew-tap"
    install: |
      bin.install "cosm"
