name: goreleaser
on:
  push:
    tags:
      - "*"
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Unshallow
        run: git fetch --prune --unshallow
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "14"
      - name: make ui
        run: make ui
      - name: Run packr2
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          go get -u github.com/gobuffalo/packr/v2/packr2
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
